pub(crate) use super::harness::{
    client_for, http_response, http_response_with_headers, mock_server_with_gated_body,
    mock_server_with_gated_chunked_body, mock_server_with_requests,
};

pub(crate) use larksuite_oapi_sdk_rs::FormDataBuilder;
pub(crate) use larksuite_oapi_sdk_rs::req::RequestOption;
pub(crate) use larksuite_oapi_sdk_rs::service::{
    acs::v1::{
        CreateRuleExternalQuery as CreateAcsRuleExternalQuery, CreateRuleExternalReqBody,
        CreateVisitorQuery, CreateVisitorReqBody,
        DeleteRuleExternalQuery as DeleteAcsRuleExternalQuery, DeleteVisitorQuery,
        DeviceBindRuleExternalQuery, DeviceBindRuleExternalReqBody, DeviceExternal, Feature,
        GetAccessRecordAccessPhotoQuery, GetRuleExternalQuery, GetUserFaceQuery,
        GetUserQuery as GetAcsUserQuery, ListAccessRecordQuery as ListAcsAccessRecordQuery,
        ListDeviceQuery, ListUserQuery as ListAcsUserQuery, OpeningTimeExternal,
        OpeningTimePeriodExternal, PatchUserQuery as PatchAcsUserQuery, Rule, UpdateUserFaceQuery,
        UpdateUserFaceReqBody, User, UserExternal,
    },
    admin::v1::{
        CreateBadgeGrantQuery, CreateBadgeGrantReqBody, CreateBadgeImageQuery, CreateBadgeQuery,
        CreateBadgeReqBody, DeleteBadgeGrantQuery, GetAdminDeptStatQuery, GetBadgeGrantQuery,
        GetBadgeQuery, ListAdminDeptStatQuery, ListAdminUserStatQuery, ListAuditInfoQuery,
        ListBadgeGrantQuery, ListBadgeQuery, ResetPasswordQuery, ResetPasswordReqBody,
        UpdateBadgeGrantQuery, UpdateBadgeQuery,
    },
    application::v1::{
        CheckUserAdminQuery as CheckApplicationV1UserAdminQuery,
        CheckUserInAppBlacklistQuery as CheckApplicationV1BlacklistQuery,
        CheckUserIsInAppBlacklistReqBody, DepartmentOverviewAppUsageQuery,
        GetAppQuery as GetApplicationV1AppQuery,
        GetAppVersionQuery as GetApplicationV1AppVersionQuery,
        ListAppQuery as ListApplicationV1AppQuery,
        ListAppVersionQuery as ListApplicationV1AppVersionQuery, OverviewAppUsageQuery,
    },
    application::v5::{FavouriteApplicationQuery, RecommendApplicationQuery},
    application::v6::{
        AppBadge, Application, ApplicationAppVersion, ApplicationContactsRangeConfigurationQuery,
        ApplyScopeQuery, CheckWhiteBlackListApplicationVisibilityQuery,
        CheckWhiteBlackListApplicationVisibilityReqBody,
        ContactsRangeSuggestApplicationAppVersionQuery, DepartmentOverviewApplicationAppUsageQuery,
        DepartmentOverviewApplicationAppUsageReqBody,
        GetApplicationAppVersionQuery as GetApplicationV6AppVersionQuery,
        GetApplicationCollaboratorsQuery, GetApplicationQuery as GetApplicationV6Query,
        ListAppRecommendRuleQuery, ListApplicationAppVersionQuery, ListApplicationFeedbackQuery,
        ListApplicationQuery as ListApplicationV6Query,
        ListScopeQuery as ListApplicationV6ScopeQuery, MessagePushOverviewApplicationAppUsageQuery,
        MessagePushOverviewApplicationAppUsageReqBody, OverviewApplicationAppUsageQuery,
        OverviewApplicationAppUsageReqBody, PatchApplicationAppVersionQuery,
        PatchApplicationContactsRangeQuery, PatchApplicationContactsRangeReqBody,
        PatchApplicationFeedbackQuery, PatchApplicationQuery, PatchApplicationVisibilityQuery,
        PatchApplicationVisibilityReqBody, SetAppBadgeQuery, UnderauditlistApplicationQuery,
        UpdateApplicationCollaboratorsQuery, UpdateApplicationCollaboratorsReqBody,
        UpdateApplicationManagementQuery, UpdateApplicationManagementReqBody,
        UpdateApplicationOwnerQuery, UpdateApplicationOwnerReqBody,
    },
    application::v7::{
        AppAbilityBot, AppAbilityWeb, AppConfigCallback, AppConfigScope, AppConfigScopeItem,
        AppI18nInfo, CreateAppAvatarUploadQuery, CreateApplicationPublishQuery,
        CreateApplicationPublishReqBody, PatchApplicationAbilityQuery,
        PatchApplicationAbilityReqBody, PatchApplicationBaseQuery, PatchApplicationBaseReqBody,
        PatchApplicationConfigQuery, PatchApplicationConfigReqBody,
    },
    approval::v4::{
        CcSearch, GetApprovalQuery, GetExternalApprovalQuery, GetInstanceQuery, InstanceSearch,
        ListExternalTaskQuery, ListExternalTaskReqBody, ListInstanceCommentQuery,
        ListInstanceQuery, QueryInstanceQuery, QueryTaskQuery as QueryApprovalTaskQuery,
        SearchCcInstanceQuery, SearchTaskQuery, TaskSearch,
    },
    attendance::v1::{
        AttendanceGroup, BatchGetUserSettingQuery, BatchGetUserSettingReqBody,
        CreateGroupQuery as CreateAttendanceGroupQuery, CreateOrUpdateGroupReqBody,
        GetApprovalInfoQuery as GetAttendanceApprovalInfoQuery, GetApprovalInfoReqBody,
        GetGroupQuery as GetAttendanceGroupQuery, ListArchiveRuleQuery,
        ListGroupQuery as ListAttendanceGroupQuery, ListLeaveAccrualQuery,
        ListShiftQuery as ListAttendanceShiftQuery, ListUserGroupQuery,
        PatchLeaveAccrualRecordQuery, PatchLeaveAccrualRecordReqBody,
        QueryRecordQuery as QueryAttendanceRecordQuery, QueryRecordReqBody,
    },
    auth::v3::{
        CreateAppAccessTokenQuery, CreateAppAccessTokenReqBody, CreateTenantAccessTokenQuery,
        CreateTenantAccessTokenReqBody, InternalAppAccessTokenQuery, InternalAppAccessTokenReqBody,
        InternalTenantAccessTokenQuery, InternalTenantAccessTokenReqBody, ResendAppTicketQuery,
        ResendAppTicketReqBody,
    },
    authen::v1::{
        CreateAccessTokenQuery as CreateAuthenAccessTokenQuery, CreateAccessTokenReqBody,
        CreateOidcAccessTokenQuery, CreateOidcAccessTokenReqBody,
        CreateOidcRefreshAccessTokenQuery, CreateOidcRefreshAccessTokenReqBody,
        CreateRefreshAccessTokenQuery, CreateRefreshAccessTokenReqBody, GetUserInfoQuery,
    },
    baike::v1::{
        CreateDraftQuery as CreateBaikeDraftQuery, CreateEntityQuery as CreateBaikeEntityQuery,
        CreateEntityReqBody as CreateBaikeEntityReqBody,
        ExtractEntityQuery as ExtractBaikeEntityQuery, GetEntityQuery as GetBaikeEntityQuery,
        HighlightEntityQuery as HighlightBaikeEntityQuery,
        ListClassificationQuery as ListBaikeClassificationQuery,
        ListEntityQuery as ListBaikeEntityQuery, MatchEntityQuery as MatchBaikeEntityQuery,
        SearchEntityQuery as SearchBaikeEntityQuery,
        SearchEntityReqBody as SearchBaikeEntityReqBody, Term as BaikeTerm,
        UpdateDraftQuery as UpdateBaikeDraftQuery, UpdateEntityQuery as UpdateBaikeEntityQuery,
        UploadFileQuery as UploadBaikeFileQuery,
    },
    base::v2::{CreateAppRoleV2Query, ListAppRoleV2Query, UpdateAppRoleV2Query},
    bitable::v1::{
        ListAppRoleMemberQuery, ListAppRoleQuery, ListAppWorkflowQuery, ListDashboardQuery,
        ListFieldQuery, ListFormFieldQuery, ListRecordQuery, ListTableQuery, ListViewQuery,
        SearchRecordQuery, SearchRecordReqBody,
    },
    block::{
        v1::{
            CreateBlockQuery as CreateBlockV1Query, CreateBlockReqBody as CreateBlockV1ReqBody,
            GetBlockQuery as GetBlockV1Query,
        },
        v2::{
            CreateEntityQuery as CreateBlockEntityQuery,
            CreateMessageQuery as CreateBlockMessageQuery,
            UpdateEntityQuery as UpdateBlockEntityQuery,
        },
    },
    board::v1::{
        BatchDeleteWhiteboardNodeQuery, BatchDeleteWhiteboardNodeReqBody, CreateBoardReqBody,
        CreatePlantumlWhiteboardNodeQuery, CreatePlantumlWhiteboardNodeReqBody,
        CreateWhiteboardNodeQuery, CreateWhiteboardNodeReqBody, CreateWhiteboardQuery,
        DownloadAsImageWhiteboardQuery, GetWhiteboardQuery, ListWhiteboardNodeQuery, Text,
        ThemeWhiteboardQuery, UpdateThemeWhiteboardQuery, UpdateThemeWhiteboardReqBody,
        WhiteboardNode,
    },
    calendar::v4::{
        BatchFreeBusyQuery, BatchFreeBusyReqBody, GetCalendarQuery,
        GetEventQuery as GetCalendarEventQuery, InstanceViewEventQuery, InstancesEventQuery,
        ListAclQuery as ListCalendarAclQuery, ListAttendeeQuery, ListCalendarQuery,
        ListChatMemberQuery as ListCalendarChatMemberQuery,
        ListEventQuery as ListCalendarEventQuery, ListFreeBusyQuery, ListFreeBusyReqBody,
        ListTimeZoneQuery, SearchCalendarQuery, SearchCalendarReqBody,
        SearchEventQuery as SearchCalendarEventQuery, SearchEventReqBody,
    },
    cardkit::v1::{
        BatchUpdateCardQuery as BatchUpdateCardkitCardQuery, BatchUpdateCardReqBody,
        ContentCardElementQuery as ContentCardkitElementQuery, ContentCardElementReqBody,
        CreateCardElementQuery as CreateCardkitElementQuery, CreateCardElementReqBody,
        CreateCardInstanceQuery as CreateCardkitInstanceQuery, CreateCardInstanceReqBody,
        CreateCardQuery as CreateCardkitCardQuery, CreateCardReqBody,
        DeleteCardElementQuery as DeleteCardkitElementQuery,
        IdConvertCardQuery as IdConvertCardkitCardQuery, IdConvertCardReqBody,
        PatchCardElementQuery as PatchCardkitElementQuery, PatchCardElementReqBody,
        SettingsCardQuery as SettingsCardkitCardQuery, SettingsCardReqBody,
        UpdateCardElementQuery as UpdateCardkitElementQuery, UpdateCardElementReqBody,
        UpdateCardInstanceQuery as UpdateCardkitInstanceQuery, UpdateCardInstanceReqBody,
        UpdateCardQuery as UpdateCardkitCardQuery, UpdateCardReqBody,
    },
    common::PageQuery,
    contact::v3::{
        BatchCreateFunctionalRoleMemberQuery, BatchCreateFunctionalRoleMemberReqBody,
        BatchDeleteFunctionalRoleMemberQuery, BatchDeleteFunctionalRoleMemberReqBody,
        BatchDepartmentQuery as BatchContactDepartmentQuery, BatchGetIdUserQuery,
        BatchGetIdUserReqBody, BatchUserQuery as BatchContactUserQuery, ChildrenDepartmentQuery,
        FindUserByDepartmentQuery, GetDepartmentQuery as GetContactDepartmentQuery,
        GetFunctionalRoleMemberQuery as GetContactFunctionalRoleMemberQuery,
        GetGroupQuery as GetContactGroupQuery, GetUserQuery as GetContactUserQuery,
        ListCustomAttrQuery, ListDepartmentQuery, ListDepartmentUnitQuery,
        ListEmployeeTypeEnumQuery,
        ListFunctionalRoleMemberQuery as ListContactFunctionalRoleMemberQuery,
        ListJobFamilyQuery as ListContactJobFamilyQuery,
        ListJobLevelQuery as ListContactJobLevelQuery,
        ListJobTitleQuery as ListContactJobTitleQuery, ListScopeQuery, ListUnitQuery,
        ListUserQuery, ListWorkCityQuery, MemberBelongGroupQuery, ResurrectUserQuery,
        ResurrectUserReqBody, ScopesFunctionalRoleMemberQuery, ScopesFunctionalRoleMemberReqBody,
        SearchDepartmentQuery, SearchDepartmentReqBody, SimplelistGroupMemberQuery,
        SimplelistGroupQuery, UnbindDepartmentChatQuery, UnbindDepartmentChatReqBody,
        UserDepartmentInfo,
    },
    corehr::v1::{
        GetDepartmentQuery as GetCorehrDepartmentQuery, GetEmployeeQuery as GetCorehrEmployeeQuery,
        ListCompanyQuery as ListCorehrCompanyQuery, ListContractQuery as ListCorehrContractQuery,
        ListCountryRegionQuery as ListCorehrCountryRegionQuery,
        ListCurrencyQuery as ListCorehrCurrencyQuery,
        ListDepartmentQuery as ListCorehrDepartmentQuery,
        ListEmployeeQuery as ListCorehrEmployeeQuery,
        ListEmployeeTypeQuery as ListCorehrEmployeeTypeQuery,
        ListJobDataQuery as ListCorehrJobDataQuery, ListJobFamilyQuery as ListCorehrJobFamilyQuery,
        ListJobLevelQuery as ListCorehrJobLevelQuery, ListJobQuery as ListCorehrJobQuery,
        ListLocationQuery as ListCorehrLocationQuery,
        ListNationalIdTypeQuery as ListCorehrNationalIdTypeQuery,
        ListPreHireQuery as ListCorehrPreHireQuery,
        ListSecurityGroupQuery as ListCorehrSecurityGroupQuery,
        ListSubdivisionQuery as ListCorehrSubdivisionQuery,
        ListSubregionQuery as ListCorehrSubregionQuery,
        ListWorkingHoursTypeQuery as ListCorehrWorkingHoursTypeQuery,
        SearchOffboardingQuery as SearchCorehrOffboardingQuery,
    },
    corehr::v2::{
        ListApproverV2Query as ListCorehrApproverV2Query, ListBpV2Query as ListCorehrBpV2Query,
        ListByBizIdSignatureFileV2Query as ListCorehrSignatureFileByBizIdV2Query,
        ListByFileIdSignatureNodeV2Query as ListCorehrSignatureNodeByFileIdV2Query,
        ListJobV2Query as ListCorehrJobV2Query, ListProcessV2Query as ListCorehrProcessV2Query,
        ListSignatureFileV2Query as ListCorehrSignatureFileV2Query,
        ListSignatureTemplateInfoWithThumbnailV2Query as ListCorehrSignatureTemplateInfoWithThumbnailV2Query,
        ListWorkforcePlanV2Query as ListCorehrWorkforcePlanV2Query,
        SearchSignatureTemplateV2Query as SearchCorehrSignatureTemplateV2Query,
    },
    directory::{
        CollaborationRuleReqBody, CreateCollaborationRuleQuery,
        CreateDepartmentQuery as CreateDirectoryDepartmentQuery, CreateDepartmentReqBody,
        CreateDirectoryEmployeeQuery, CreateEmployeeReqBody, DeleteCollaborationRuleQuery,
        DeleteDepartmentQuery, DeleteDirectoryEmployeeQuery, DeleteEmployeeReqBody,
        ListCollaborationRuleQuery, ListCollaborationTenantQuery, ListDirectoryUserQuery,
        ListShareEntityQuery, MgetEmployeeQuery as MgetDirectoryEmployeeQuery, MgetEmployeeReqBody,
        PatchEmployeeQuery as PatchDirectoryEmployeeQuery, PatchEmployeeReqBody,
        RegularDirectoryEmployeeQuery, RegularEmployeeReqBody, ResurrectDirectoryEmployeeQuery,
        ResurrectEmployeeReqBody, SearchDepartmentReqBody as DirectorySearchDepartmentReqBody,
        SearchDirectoryDepartmentQuery, ToBeResignedDirectoryEmployeeQuery,
        ToBeResignedEmployeeReqBody, UpdateCollaborationRuleQuery,
    },
    docs::v1::{GetContentQuery as GetDocsContentQuery, GetDocumentQuery as GetDocsDocumentQuery},
    docx::v1::{
        BatchDeleteChatAnnouncementBlockChildrenQuery, BatchUpdateBlockReqBody,
        BatchUpdateChatAnnouncementBlockQuery, BatchUpdateDocumentBlockQuery, Block as DocxBlock,
        ConvertDocumentQuery, CreateBlockReqBody, CreateChatAnnouncementBlockChildrenQuery,
        CreateDocumentBlockDescendantQuery, CreateDocumentBlockQuery, CreateDocumentQuery,
        CreateDocumentReqBody, DeleteBlocksReqBody, DeleteDocumentBlockChildrenQuery,
        GetBuildingBlockQuery, GetChatAnnouncementBlockChildrenQuery,
        GetChatAnnouncementBlockQuery, GetChatAnnouncementQuery as GetDocxChatAnnouncementQuery,
        GetDocumentBlockQuery, GetDocumentQuery as GetDocxDocumentQuery,
        GetDocumentRawContentQuery, ListChatAnnouncementBlockQuery, ListDocumentBlockChildrenQuery,
        ListDocumentBlockQuery, UpdateBlockReqBody, UpdateDocumentBlockQuery,
        UpdateTextElementsRequest,
    },
    drive::{
        v1::{
            BatchQueryFileCommentQuery, BatchQueryFileCommentReqBody, GetFileCommentQuery,
            GetPermissionPublicQuery as GetDrivePermissionPublicQuery, ListFileCommentQuery,
            ListFileCommentReplyQuery, ListFileQuery, ListFileVersionQuery,
            ListFileViewRecordQuery, ListPermissionMemberQuery,
        },
        v2::{
            GetPermissionPublicV2Query as GetDrivePermissionPublicV2Query, ListFileLikeQuery,
            PatchPermissionPublicV2Query as PatchDrivePermissionPublicV2Query,
            PatchPermissionPublicV2ReqBody,
        },
    },
    ehr::v1::ListEmployeeQuery as ListEhrEmployeeQuery,
    event::v1::ListOutboundIpQuery,
    face_detection::v1::{DetectFaceAttributesQuery, RecognizeReqBody as FaceRecognizeReqBody},
    helpdesk::v1::{
        CustomizedFieldsTicketQuery, GetAgentSchedulesQuery, GetCategoryQuery,
        GetFaqQuery as GetHelpdeskFaqQuery, GetTicketQuery, ListAgentQuery, ListAgentScheduleQuery,
        ListCategoryQuery, ListFaqQuery, ListTicketMessageQuery, ListTicketQuery, SearchFaqQuery,
    },
    hire::v1::{
        BatchQueryAgencyQuery as BatchQueryHireAgencyQuery,
        BatchQueryExternalBackgroundCheckQuery as BatchQueryHireExternalBackgroundCheckQuery,
        BatchQueryExternalInterviewQuery as BatchQueryHireExternalInterviewQuery,
        BatchQueryExternalOfferQuery as BatchQueryHireExternalOfferQuery,
        GetAgencyAccountQuery as GetHireAgencyAccountQuery, GetAgencyQuery as GetHireAgencyQuery,
        GetApplicationQuery as GetHireApplicationQuery,
        GetByApplicationEmployeeQuery as GetHireByApplicationEmployeeQuery,
        GetByTalentInterviewQuery as GetHireByTalentInterviewQuery,
        GetInterviewRecordAttachmentQuery as GetHireInterviewRecordAttachmentQuery,
        GetJobQuery as GetHireJobQuery, GetMinutesQuery as GetHireMinutesQuery,
        GetOfferQuery as GetHireOfferQuery, GetReferralQuery as GetHireReferralQuery,
        GetTalentQuery as GetHireTalentQuery,
        ListApplicationInterviewQuery as ListHireApplicationInterviewQuery,
        ListApplicationQuery as ListHireApplicationQuery,
        ListBackgroundCheckOrderQuery as ListHireBackgroundCheckOrderQuery,
        ListByIdJobRequirementQuery as ListByIdHireJobRequirementQuery,
        ListEvaluationQuery as ListHireEvaluationQuery,
        ListEvaluationTaskQuery as ListHireEvaluationTaskQuery,
        ListExamMarkingTaskQuery as ListHireExamMarkingTaskQuery,
        ListExternalApplicationQuery as ListHireExternalApplicationQuery,
        ListInterviewFeedbackFormQuery as ListHireInterviewFeedbackFormQuery,
        ListInterviewQuery as ListHireInterviewQuery,
        ListInterviewRecordQuery as ListHireInterviewRecordQuery,
        ListInterviewRegistrationSchemaQuery as ListHireInterviewRegistrationSchemaQuery,
        ListInterviewRoundTypeQuery as ListHireInterviewRoundTypeQuery,
        ListInterviewTaskQuery as ListHireInterviewTaskQuery,
        ListInterviewerQuery as ListHireInterviewerQuery,
        ListJobFunctionQuery as ListHireJobFunctionQuery,
        ListJobProcessQuery as ListHireJobProcessQuery, ListJobQuery as ListHireJobQuery,
        ListJobRequirementQuery as ListHireJobRequirementQuery,
        ListJobRequirementSchemaQuery as ListHireJobRequirementSchemaQuery,
        ListJobSchemaQuery as ListHireJobSchemaQuery, ListJobTypeQuery as ListHireJobTypeQuery,
        ListLocationQuery as ListHireLocationQuery, ListNoteQuery as ListHireNoteQuery,
        ListOfferApplicationFormQuery as ListHireOfferApplicationFormQuery,
        ListOfferApprovalTemplateQuery as ListHireOfferApprovalTemplateQuery,
        ListOfferQuery as ListHireOfferQuery,
        ListPortalApplySchemaQuery as ListHirePortalApplySchemaQuery,
        ListQuestionnaireQuery as ListHireQuestionnaireQuery,
        ListReferralWebsiteJobPostQuery as ListHireReferralWebsiteJobPostQuery,
        ListRegistrationSchemaQuery as ListHireRegistrationSchemaQuery,
        ListResumeSourceQuery as ListHireResumeSourceQuery, ListRoleQuery as ListHireRoleQuery,
        ListSubjectQuery as ListHireSubjectQuery,
        ListTalentFolderQuery as ListHireTalentFolderQuery, ListTalentQuery as ListHireTalentQuery,
        ListTalentTagQuery as ListHireTalentTagQuery,
        ListTerminationReasonQuery as ListHireTerminationReasonQuery,
        ListTodoQuery as ListHireTodoQuery,
        ListTripartiteAgreementQuery as ListHireTripartiteAgreementQuery,
        ListUserRoleQuery as ListHireUserRoleQuery,
        ListWebsiteChannelQuery as ListHireWebsiteChannelQuery,
        ListWebsiteJobPostQuery as ListHireWebsiteJobPostQuery,
        ListWebsiteQuery as ListHireWebsiteQuery, QueryAgencyQuery as QueryHireAgencyQuery,
        QueryLocationQuery as QueryHireLocationQuery,
        SearchJobPublishRecordQuery as SearchHireJobPublishRecordQuery,
        SearchReferralQuery as SearchHireReferralQuery,
        SearchTalentOperationLogQuery as SearchHireTalentOperationLogQuery,
        SearchTalentPoolQuery as SearchHireTalentPoolQuery, SearchTestQuery as SearchHireTestQuery,
        SearchWebsiteJobPostQuery as SearchHireWebsiteJobPostQuery,
    },
    hire::v2::{
        GetInterviewRecordV2Query as GetHireV2InterviewRecordQuery,
        GetTalentV2Query as GetHireV2TalentQuery,
        ListInterviewRecordV2Query as ListHireV2InterviewRecordQuery,
    },
    human_authentication::v1::{
        CreateIdentityQuery as CreateHumanIdentityQuery, CreateIdentityReqBody,
    },
    im::v1::{
        GetChatAnnouncementQuery, GetChatMembersQuery, GetChatModerationQuery,
        GetChatQuery as GetImChatQuery, GetMessageQuery as GetImMessageQuery,
        GetMessageResourceDownloadQuery, IsInChatMembersQuery, ListChatQuery as ListImChatQuery,
        ListMessageQuery as ListImMessageQuery, ListMessageReactionQuery, ListPinQuery,
        ReadUsersMessageQuery, SearchChatQuery as SearchImChatQuery,
    },
    im::v2::{
        BatchUpdateUrlPreviewV2Query, BatchUpdateUrlPreviewV2ReqBody,
        BizEntityTagRelationV2ReqBody, BotTimeSensitiveFeedCardV2Query,
        BotTimeSensitiveFeedCardV2ReqBody, CreateAppFeedCardV2Query, CreateAppFeedCardV2ReqBody,
        CreateBizEntityTagRelationV2Query, CreateTagV2Query, CreateTagV2ReqBody,
        DeleteAppFeedCardBatchV2Query, DeleteAppFeedCardBatchV2ReqBody,
        GetBizEntityTagRelationV2Query, PatchFeedCardV2Query, PatchFeedCardV2ReqBody,
        PatchTagV2Query, PatchTagV2ReqBody, UpdateAppFeedCardBatchV2Query,
        UpdateAppFeedCardBatchV2ReqBody, UpdateBizEntityTagRelationV2Query,
        UpdateChatButtonV2Query, UpdateChatButtonV2ReqBody,
    },
    lingo::v1::{
        CreateDraftQuery as CreateLingoDraftQuery, CreateEntityQuery as CreateLingoEntityQuery,
        CreateLingoEntityReqBody, DeleteEntityQuery as DeleteLingoEntityQuery,
        GetEntityQuery as GetLingoEntityQuery, HighlightEntityQuery, LingoTerm,
        ListClassificationQuery as ListLingoClassificationQuery,
        ListEntityQuery as ListLingoEntityQuery, ListRepoQuery as ListLingoRepoQuery,
        MatchEntityQuery, SearchEntityQuery as SearchLingoEntityQuery, SearchLingoEntityReqBody,
        UpdateDraftQuery as UpdateLingoDraftQuery, UpdateEntityQuery as UpdateLingoEntityQuery,
        UploadFileQuery as UploadLingoFileQuery,
    },
    mail::v1::{
        BatchCreateMailgroupMemberQuery, BatchCreateMailgroupMemberReqBody,
        BatchCreatePublicMailboxMemberQuery, BatchCreatePublicMailboxMemberReqBody,
        BatchDeleteMailgroupMemberQuery, BatchDeleteMailgroupMemberReqBody,
        BatchDeletePublicMailboxMemberQuery, BatchDeletePublicMailboxMemberReqBody,
        CreateMailgroupMemberQuery, CreateMailgroupQuery, CreateMailgroupReqBody,
        CreatePublicMailboxMemberQuery, CreatePublicMailboxQuery, CreatePublicMailboxReqBody,
        GetMailgroupMemberQuery, GetMailgroupQuery, GetPublicMailboxMemberQuery,
        GetPublicMailboxQuery, ListMailgroupMemberQuery as ListMailMailgroupMemberQuery,
        ListMailgroupQuery as ListMailMailgroupQuery,
        ListPublicMailboxMemberQuery as ListMailPublicMailboxMemberQuery,
        ListPublicMailboxQuery as ListMailPublicMailboxQuery, MailgroupMember, PatchMailgroupQuery,
        PatchPublicMailboxQuery, PublicMailboxMember, UpdateMailgroupQuery,
        UpdatePublicMailboxQuery,
    },
    mdm::v1::{
        BindUserAuthDataRelationQuery, ListUserDeviceQuery, UnbindUserAuthDataRelationQuery,
        UpdateDeviceReqBody, UpdateUserDeviceQuery,
    },
    mdm::v3::{GetBatchCountryRegionV3Query, ListCountryRegionV3Query},
    meeting_room::v1::{
        ListBuildingQuery as ListMeetingRoomBuildingQuery, ListRoomQuery as ListMeetingRoomQuery,
    },
    minutes::v1::{
        GetMinutesQuery as GetMinutesMinutesQuery, GetTranscriptQuery as GetMinutesTranscriptQuery,
        ListParticipantQuery as ListMinutesParticipantQuery,
    },
    moments::v1::{GetPostQuery, ListPostQuery},
    okr::v1::{
        BatchGetOkrQuery, CreatePeriodQuery as CreateOkrPeriodQuery, CreateProgressRecordQuery,
        DeleteProgressRecordQuery, GetProgressRecordQuery, GetUserOkrQuery,
        ListPeriodQuery as ListOkrPeriodQuery, ListPeriodRuleQuery,
        PatchPeriodQuery as PatchOkrPeriodQuery, QueryReviewQuery, UpdateProgressRecordQuery,
        UploadImageQuery as UploadOkrImageQuery,
    },
    optical_char_recognition::v1::{BasicRecognizeImageQuery, RecognizeBasicImageReqBody},
    passport::v1::{
        LogoutSessionQuery, LogoutSessionReqBody, QuerySessionQuery, QuerySessionReqBody,
    },
    payroll::v1::{
        ArchivePaymentActivityQuery, ListCostAllocationDetailQuery, ListPaymentActivityDetailQuery,
        ListPaymentActivityQuery, ListPayrollRecordQuery, QueryDatasourceRecordQuery,
        QueryPaymentDetailQuery, SaveDatasourceRecordQuery,
    },
    performance::{
        v1::ListActivityQuery as ListPerformanceActivityQuery,
        v2::{
            DeleteAdditionalInformationsBatchV2Query, ImportAdditionalInformationV2Query,
            ImportMetricDetailV2Query, ListMetricTagV2Query as ListPerformanceMetricTagV2Query,
            QueryActivityV2Query, QueryAdditionalInformationV2Query, QueryIndicatorV2Query,
            QueryMetricDetailV2Query, QueryMetricFieldV2Query, QueryMetricLibV2Query,
            QueryMetricTemplateV2Query, QueryQuestionV2Query, QueryReviewDataV2Query,
            QueryReviewTemplateV2Query, QueryRevieweeV2Query, QueryUserInfoV2Query,
            WriteUserGroupUserRelV2Query,
        },
    },
    personal_settings::v1::{
        BatchCloseSystemStatusQuery, BatchOpenSystemStatusQuery, BatchOpenSystemStatusReqBody,
        CreateSystemStatusQuery, CreateSystemStatusReqBody, DeleteSystemStatusQuery,
        ListSystemStatusQuery, PatchSystemStatusQuery, SystemStatus,
    },
    report::v1::{
        QueryRuleQuery as QueryReportRuleQuery, QueryTaskQuery as QueryReportTaskQuery,
        QueryTaskReqBody as QueryReportTaskReqBody, RemoveRuleViewQuery, RemoveRuleViewReqBody,
    },
    search::v2::{
        CreateAppSearchQuery, CreateDataRecordQuery, CreateDataRecordReqBody,
        CreateDataSourceQuery, CreateDataSourceReqBody, CreateDataSourceSchemaQuery,
        CreateMessageSearchQuery, CreateSchemaQuery, CreateSchemaReqBody, DataRecordContent,
        DataRecordMetadata, DeleteDataRecordQuery, DeleteDataSourceQuery,
        DeleteDataSourceSchemaQuery, DeleteSchemaQuery, DocFilter, GetDataRecordQuery,
        GetDataSourceQuery, GetDataSourceSchemaQuery, GetSchemaQuery, ListDataSourceQuery,
        PatchDataSourceQuery, PatchDataSourceReqBody, PatchDataSourceSchemaQuery, PatchSchemaQuery,
        PatchSchemaReqBody, SchemaProperty, SearchAppReqBody, SearchDocWikiQuery,
        SearchDocWikiReqBody, SearchMessageReqBody,
    },
    security_and_compliance::{
        v1::ListOpenapiLogQuery,
        v2::{
            CreateDeviceRecordV2Query, DeleteDeviceRecordV2Query, GetDeviceRecordV2Query,
            ListDeviceRecordV2Query, MineDeviceRecordV2Query, UpdateDeviceApplyRecordV2Query,
            UpdateDeviceRecordV2Query,
        },
    },
    spark::v1::{
        DownloadAppStorageQuery, SparkPageQuery, SparkRecordQuery, SparkTableMutationQuery,
        SparkViewRecordQuery,
    },
    speech_to_text::v1::{
        FileRecognizeSpeechQuery, RecognizeBasicSpeechReqBody, RecognizeSpeechStreamReqBody,
        StreamRecognizeSpeechQuery,
    },
    task::{
        BatchDeleteCollaboratorQuery, BatchDeleteFollowerQuery, CompleteTaskQuery,
        CreateCollaboratorQuery, CreateCollaboratorReqBody,
        CreateCommentQuery as CreateTaskCommentQuery, CreateCommentReqBody, CreateFollowerQuery,
        CreateFollowerReqBody, CreateReminderQuery, CreateReminderReqBody,
        CreateTaskQuery as CreateTaskV1Query, CreateTaskReqBody, DeleteCollaboratorQuery,
        DeleteCommentQuery, DeleteFollowerQuery, DeleteReminderQuery, DeleteTaskQuery,
        GetCommentQuery as GetTaskCommentQuery, GetReminderQuery, GetTaskQuery as GetTaskV1Query,
        ListCollaboratorQuery, ListCommentQuery as ListTaskCommentQuery, ListFollowerQuery,
        ListReminderQuery, ListTaskQuery, PatchTaskQuery as PatchTaskV1Query, PatchTaskReqBody,
        Task, UncompleteTaskQuery, UpdateCommentQuery as UpdateTaskCommentQuery,
        UpdateCommentReqBody, UpdateReminderQuery, UpdateReminderReqBody,
        v2::{
            AddCustomFieldV2Query, AddMembersTaskV2Query, AddMembersTaskV2ReqBody,
            AddMembersTasklistV2Query, AddOrRemoveCustomFieldV2ReqBody,
            CreateActivitySubscriptionV2Query, CreateCommentV2Query,
            CreateCustomFieldOptionV2Query, CreateCustomFieldV2Query, CreateSectionV2Query,
            CreateTaskSubtaskV2Query, CreateTaskV2Query, CreateTasklistV2Query,
            DeleteActivitySubscriptionV2Query, DeleteAttachmentV2Query, DeleteCommentV2Query,
            DeleteSectionV2Query, DeleteTaskV2Query, DeleteTasklistV2Query,
            GetActivitySubscriptionV2Query, GetAttachmentV2Query, GetCommentV2Query,
            GetCustomFieldV2Query, GetSectionV2Query, GetTaskV2Query, GetTasklistV2Query,
            ListActivitySubscriptionV2Query, ListAttachmentV2Query, ListCommentV2Query,
            ListCustomFieldV2Query, ListSectionV2Query, ListTaskSubtaskV2Query, ListTaskV2Query,
            ListTasklistV2Query, MembersTaskV2ReqBody, PatchActivitySubscriptionV2Query,
            PatchActivitySubscriptionV2ReqBody, PatchCommentV2Query, PatchCommentV2ReqBody,
            PatchCustomFieldOptionV2Query, PatchCustomFieldOptionV2ReqBody,
            PatchCustomFieldV2Query, PatchCustomFieldV2ReqBody, PatchSectionV2Query,
            PatchSectionV2ReqBody, PatchTaskV2Query, PatchTaskV2ReqBody, PatchTasklistV2Query,
            PatchTasklistV2ReqBody, RemoveCustomFieldV2Query, RemoveMembersTasklistV2Query,
            TaskListParams, TaskV2ActivitySubscriptionInput, TaskV2InputComment,
            TaskV2InputCustomField, TaskV2InputOption, TaskV2InputSection, TaskV2InputTask,
            TaskV2InputTasklist, TasklistsTaskV2Query, TasksSectionV2Query, TasksTasklistV2Query,
            UploadAttachmentV2Query,
        },
    },
    tenant::v2::{QueryTenantProductAssignInfoQuery, QueryTenantQuery},
    translation::v1::{
        DetectLanguageQuery, DetectLanguageReqBody, TranslateReqBody, TranslateTextQuery,
    },
    trust_party::v1::{
        GetCollaborationTenantCollaborationDepartmentQuery,
        GetCollaborationTenantCollaborationUserQuery, GetCollaborationTenantQuery,
        ListCollaborationTenantQuery as ListTrustPartyCollaborationTenantQuery,
        VisibleOrganizationCollaborationTenantQuery,
    },
    vc::{
        ApplyReserveQuery, CreateRoomQuery as CreateVcRoomQuery, CreateRoomReqBody,
        GetActiveMeetingReserveQuery, GetMeetingListQuery, GetParticipantListQuery,
        GetParticipantQualityListQuery, GetReserveQuery, GetResourceReservationListQuery,
        GetRoomQuery as GetVcRoomQuery, GetTopUserReportQuery, ListAlertQuery,
        ListMeetingByNoQuery, ListRoomQuery as ListVcRoomQuery, MgetRoomQuery, RoomConfigQuery,
        SearchRoomQuery, SetRoomConfigQuery, SetRoomConfigReqBody, UpdateReserveQuery,
        UpdateRoomQuery as UpdateVcRoomQuery, UpdateRoomReqBody,
    },
    verification::v1::{
        CreateVerificationTaskQuery, CreateVerificationTaskReqBody, GetVerificationQuery,
        GetVerificationTaskQuery,
    },
    wiki::v1::SearchNodeV1Query,
    workplace::v1::{
        CustomWorkplaceAccessDataQuery, WorkplaceAccessDataQuery, WorkplaceBlockAccessDataQuery,
    },
};
